// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZzr9gKnpqXqJczpbIZJ9cnYxTEejGIDI',
    appId: '1:832175534179:web:1a6fe46a7c998e5dc34856',
    messagingSenderId: '832175534179',
    projectId: 'chameleon-4d8c1',
    authDomain: 'chameleon-4d8c1.firebaseapp.com',
    storageBucket: 'chameleon-4d8c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3JpygZQmCGMNaekC0uFYPWE8xeeNjhLs',
    appId: '1:832175534179:android:6af4cd81f64512e6c34856',
    messagingSenderId: '832175534179',
    projectId: 'chameleon-4d8c1',
    storageBucket: 'chameleon-4d8c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOwTi2k21wYybqrmwyXwYA1Ek30TNaRJk',
    appId: '1:832175534179:ios:790235e149506e57c34856',
    messagingSenderId: '832175534179',
    projectId: 'chameleon-4d8c1',
    storageBucket: 'chameleon-4d8c1.appspot.com',
    iosBundleId: 'com.example.chameleon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOwTi2k21wYybqrmwyXwYA1Ek30TNaRJk',
    appId: '1:832175534179:ios:25d6ed05b91f99d1c34856',
    messagingSenderId: '832175534179',
    projectId: 'chameleon-4d8c1',
    storageBucket: 'chameleon-4d8c1.appspot.com',
    iosBundleId: 'com.example.chameleon.RunnerTests',
  );
}
